### ISSUE TITLE
Only strings in conditional tests

### ISSUE THREAD

**Issue by elliottinvent** [MODLanguage/grammar#24]
At the moment we can only test a string, e.g:

```
_test="http://www.tesco.com"

result={
  test="http://www.tesco.com"?
      yes
  /?
     no
}
```

Due to this rule in the grammar:

```
modl_condition
  // e.g. country=gb
  : NEWLINE* STRING? modl_operator? modl_value (PIPE modl_value )* NEWLINE*
;
```

This means we can't quote a test or use a number as the test. I can't really come up with any reasons why someone would need to do this but interested in your thoughts @twalmsley @alexdalitz

**Comment by twalmsley** [comment]
At least one of the items in the comparison should be a variable, such as the value of `a` in `{a=1?}` since having two constants doesn't seem to make sense, so I think its ok to require the variable name to be on the left so that `{a=1?}` is allowed but `{1=a?}` isn't. I don't have a problem with supporting this form if you prefer to change the grammar.
