### ISSUE TITLE
Deep object referencing in conditionals

### ISSUE THREAD

**Issue by elliottinvent** [MODLanguage/grammar#27]
This works:
```
_array[1;2]
_array_item=%array>0
test={
  array_item=1?
     yes
  /?
     no
}
```
->
```
{
    "test": "yes"
}
```
But this doesn't:
```
_array[1;2]
test={
  array>0=1?
     yes
  /?
     no
}
```
-> `line 3:10 no viable alternative at input '{\n%array>0=' `

I guess this is because it's assuming `>` is greater than in the conditional test?

**Comment by elliottinvent** [comment]
We also can't use deep object referencing in the value we're testing against, e.g:

```
_array[1;2]
_array_item=%array>0
test={
  array_item=%array>0?
     yes
  /?
     no
}
```
-> `line 4:19 no viable alternative at input '{\narray_item=%array>' `

It may be that we need to ban this and authors must assign deep object references to another object if they want to include it in a conditional. If that's the only way to do it then we just need to spec it.

**Comment by twalmsley** [comment]
As discussed elsewhere we can fix this by using dot notation instead of `>` for deep references. There are no grammar changes needed, but it did require significant changes to the Ruby interpreter (about a day's work) so I expect similar impact to the other interpreters.

I have added the test cases from the comments above and will close this when I push them to GitHub

**Comment by twalmsley** [comment]
Tests pushed - Ruby interpreter fixed. Java and JS interpreters will be updated in the coming weeks.
